# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 160, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.get_com_port_number = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_com_port_number.setObjectName("get_com_port_number")
        self.verticalLayout.addWidget(self.get_com_port_number)
        self.init_device_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.init_device_button.setObjectName("init_device_button")
        self.verticalLayout.addWidget(self.init_device_button)
        self.reset_settings_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reset_settings_button.setObjectName("reset_settings_button")
        self.verticalLayout.addWidget(self.reset_settings_button)
        self.get_version_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_version_button.setObjectName("get_version_button")
        self.verticalLayout.addWidget(self.get_version_button)
        self.set_photo_size_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.set_photo_size_button.setObjectName("set_photo_size_button")
        self.verticalLayout.addWidget(self.set_photo_size_button)
        self.set_photo_compression_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.set_photo_compression_button.setObjectName("set_photo_compression_button")
        self.verticalLayout.addWidget(self.set_photo_compression_button)
        self.get_photo_size_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_photo_size_button.setObjectName("get_photo_size_button")
        self.verticalLayout.addWidget(self.get_photo_size_button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 160, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.get_com_port_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.get_com_port_text.setClearButtonEnabled(True)
        self.get_com_port_text.setObjectName("get_com_port_text")
        self.verticalLayout_2.addWidget(self.get_com_port_text)
        self.init_device_alert = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.init_device_alert.setObjectName("init_device_alert")
        self.verticalLayout_2.addWidget(self.init_device_alert)
        self.reset_settings_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.reset_settings_text.setObjectName("reset_settings_text")
        self.verticalLayout_2.addWidget(self.reset_settings_text)
        self.get_version_output = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.get_version_output.setObjectName("get_version_output")
        self.verticalLayout_2.addWidget(self.get_version_output)
        self.choose_photo_size = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.choose_photo_size.setObjectName("choose_photo_size")
        self.verticalLayout_2.addWidget(self.choose_photo_size)
        self.choose_photo_compr = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.choose_photo_compr.setObjectName("choose_photo_compr")
        self.verticalLayout_2.addWidget(self.choose_photo_compr)
        self.get_photo_size_text = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.get_photo_size_text.setObjectName("get_photo_size_text")
        self.verticalLayout_2.addWidget(self.get_photo_size_text)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(420, 10, 561, 481))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.image_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.image_layout.setContentsMargins(0, 0, 0, 0)
        self.image_layout.setObjectName("image_layout")
        self.take_photo_alert = QtWidgets.QLineEdit(self.centralwidget)
        self.take_photo_alert.setGeometry(QtCore.QRect(170, 720, 158, 22))
        self.take_photo_alert.setClearButtonEnabled(False)
        self.take_photo_alert.setObjectName("take_photo_alert")
        self.take_photo_button = QtWidgets.QPushButton(self.centralwidget)
        self.take_photo_button.setGeometry(QtCore.QRect(0, 720, 158, 28))
        self.take_photo_button.setObjectName("take_photo_button")
        self.choose_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_path_button.setGeometry(QtCore.QRect(0, 670, 158, 28))
        self.choose_path_button.setObjectName("choose_path_button")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(420, 500, 571, 271))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_com_port_number.setText(_translate("MainWindow", "Get COM port number"))
        self.init_device_button.setText(_translate("MainWindow", "Initialize device"))
        self.reset_settings_button.setText(_translate("MainWindow", "Reset all the settings"))
        self.get_version_button.setText(_translate("MainWindow", "Get camera version"))
        self.set_photo_size_button.setText(_translate("MainWindow", "Set photo size"))
        self.set_photo_compression_button.setText(_translate("MainWindow", "Set photo compression"))
        self.get_photo_size_button.setText(_translate("MainWindow", "Get photo size (bytes)"))
        self.take_photo_button.setText(_translate("MainWindow", "Take photo"))
        self.choose_path_button.setText(_translate("MainWindow", "Save photo"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">To start taking a photo, get your COM port number first.<br />Then, Initilize your device; it will automatically read the COM port number.<br />Reset all the settings.<br />To check if the programm works correctly, get your device version.<br />Set the photo size: 320x240 or 640x480.<br />Set the photo compression: 1x, 2x or 4x.<br />Get photo size in bytes.<br />Finally, take the photo. It will be shown on the top-right side.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Choose a folder and save the photo.<br />To take another photo, set the size and compression and click &quot;Take photo&quot;</span></p></body></html>"))
